// Code generated by protoc-gen-go-kit-mux. DO NOT EDIT.
// versions:
// - protoc-gen-go-kit-mux v0.0.1-devel
// - protoc                v3.6.1
package power

import (
	uuid "github.com/google/uuid"
	http "net/http"
	sync "sync"
)

/**
 * power
 */
type PowerIndex uuid.UUID
type Power struct {
	PowerIndex `json:"power,omitempty"`
	PowerName  string `json:"-"`
	Name       string `json:"name,omitempty"`
	Method     string `json:"-"`
	URL        string `json:"-"`
	MuxPath    string `json:"-"`
}

var PowerMap = make(map[PowerIndex]*Power)

func (pi PowerIndex) Method() string {
	return PowerMap[pi].Method
}
func (pi PowerIndex) URL() string {
	return PowerMap[pi].URL
}
func (pi PowerIndex) Name() string {
	return PowerMap[pi].Name
}
func (pi PowerIndex) PowerName() string {
	return PowerMap[pi].PowerName
}
func (pi PowerIndex) MuxPath() string {
	return PowerMap[pi].MuxPath
}

var (
	PowerHealth        = PowerIndex(uuid.MustParse("57c12aa9-801f-4f39-bbaa-8aca14c3e303"))
	PowerGetDepartment = PowerIndex(uuid.MustParse("6d530c29-a015-447b-a3dc-fada94f4861c"))
)

func init() {
	var once sync.Once
	once.Do(func() {
		PowerMap[PowerHealth] = &Power{
			PowerIndex: PowerHealth,
			PowerName:  "Health",
			Name:       "健康检查",
			Method:     http.MethodGet,
			URL:        `/health`,
			MuxPath:    `/health`,
		}
		PowerMap[PowerGetDepartment] = &Power{
			PowerIndex: PowerGetDepartment,
			PowerName:  "GetDepartment",
			Name:       "获取部门详情",
			Method:     http.MethodGet,
			URL:        `/department/[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}`,
			MuxPath:    `/department/{id:[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}}`,
		}
	})
}
