// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: kit/data_type.proto

package kit

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoPkg  string `protobuf:"bytes,1,opt,name=go_pkg,json=goPkg,proto3" json:"go_pkg,omitempty"`
	GoType string `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
}

func (x *FieldType) Reset() {
	*x = FieldType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kit_data_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldType) ProtoMessage() {}

func (x *FieldType) ProtoReflect() protoreflect.Message {
	mi := &file_kit_data_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldType.ProtoReflect.Descriptor instead.
func (*FieldType) Descriptor() ([]byte, []int) {
	return file_kit_data_type_proto_rawDescGZIP(), []int{0}
}

func (x *FieldType) GetGoPkg() string {
	if x != nil {
		return x.GoPkg
	}
	return ""
}

func (x *FieldType) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

var file_kit_data_type_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*FieldType)(nil),
		Field:         82295500,
		Name:          "go.terra.kit.type",
		Tag:           "bytes,82295500,opt,name=type",
		Filename:      "kit/data_type.proto",
	},
}

// Extension fields to descriptor.FieldOptions.
var (
	// optional go.terra.kit.FieldType type = 82295500;
	E_Type = &file_kit_data_type_proto_extTypes[0] // 字段类型 "github.com/google/uuid.UUID"
)

var File_kit_data_type_proto protoreflect.FileDescriptor

var file_kit_data_type_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x69, 0x74, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x6f, 0x2e, 0x74, 0x65, 0x72, 0x72, 0x61, 0x2e,
	0x6b, 0x69, 0x74, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x67, 0x6f, 0x5f, 0x70, 0x6b, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x67, 0x6f, 0x50, 0x6b, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x6f, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x6f, 0x54, 0x79,
	0x70, 0x65, 0x3a, 0x4d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xcc, 0xf5, 0x9e, 0x27, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x2e, 0x74, 0x65, 0x72, 0x72, 0x61, 0x2e, 0x6b, 0x69,
	0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x78, 0x36, 0x34, 0x66, 0x75, 0x6e, 0x2f, 0x74, 0x65, 0x72, 0x72, 0x61, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x6b, 0x69, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kit_data_type_proto_rawDescOnce sync.Once
	file_kit_data_type_proto_rawDescData = file_kit_data_type_proto_rawDesc
)

func file_kit_data_type_proto_rawDescGZIP() []byte {
	file_kit_data_type_proto_rawDescOnce.Do(func() {
		file_kit_data_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_kit_data_type_proto_rawDescData)
	})
	return file_kit_data_type_proto_rawDescData
}

var file_kit_data_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kit_data_type_proto_goTypes = []interface{}{
	(*FieldType)(nil),               // 0: go.terra.kit.FieldType
	(*descriptor.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_kit_data_type_proto_depIdxs = []int32{
	1, // 0: go.terra.kit.type:extendee -> google.protobuf.FieldOptions
	0, // 1: go.terra.kit.type:type_name -> go.terra.kit.FieldType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kit_data_type_proto_init() }
func file_kit_data_type_proto_init() {
	if File_kit_data_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kit_data_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kit_data_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_kit_data_type_proto_goTypes,
		DependencyIndexes: file_kit_data_type_proto_depIdxs,
		MessageInfos:      file_kit_data_type_proto_msgTypes,
		ExtensionInfos:    file_kit_data_type_proto_extTypes,
	}.Build()
	File_kit_data_type_proto = out.File
	file_kit_data_type_proto_rawDesc = nil
	file_kit_data_type_proto_goTypes = nil
	file_kit_data_type_proto_depIdxs = nil
}
