// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: kit/swagger.proto

package kit

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Swagger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summary     string   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags        string   `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	Accept      string   `protobuf:"bytes,4,opt,name=accept,proto3" json:"accept,omitempty"`
	Produce     string   `protobuf:"bytes,5,opt,name=produce,proto3" json:"produce,omitempty"`
	Param       []string `protobuf:"bytes,6,rep,name=param,proto3" json:"param,omitempty"`
	Success     string   `protobuf:"bytes,7,opt,name=success,proto3" json:"success,omitempty"`
	Router      string   `protobuf:"bytes,8,opt,name=router,proto3" json:"router,omitempty"`
}

func (x *Swagger) Reset() {
	*x = Swagger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kit_swagger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Swagger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Swagger) ProtoMessage() {}

func (x *Swagger) ProtoReflect() protoreflect.Message {
	mi := &file_kit_swagger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Swagger.ProtoReflect.Descriptor instead.
func (*Swagger) Descriptor() ([]byte, []int) {
	return file_kit_swagger_proto_rawDescGZIP(), []int{0}
}

func (x *Swagger) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Swagger) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Swagger) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Swagger) GetAccept() string {
	if x != nil {
		return x.Accept
	}
	return ""
}

func (x *Swagger) GetProduce() string {
	if x != nil {
		return x.Produce
	}
	return ""
}

func (x *Swagger) GetParam() []string {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *Swagger) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *Swagger) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

var file_kit_swagger_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*Swagger)(nil),
		Field:         82295789,
		Name:          "go.kit.swagger",
		Tag:           "bytes,82295789,opt,name=swagger",
		Filename:      "kit/swagger.proto",
	},
}

// Extension fields to descriptor.MethodOptions.
var (
	// optional go.kit.Swagger swagger = 82295789;
	E_Swagger = &file_kit_swagger_proto_extTypes[0]
)

var File_kit_swagger_proto protoreflect.FileDescriptor

var file_kit_swagger_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6b, 0x69, 0x74, 0x2f, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x6f, 0x2e, 0x6b, 0x69, 0x74, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x01,
	0x0a, 0x07, 0x53, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x3a, 0x4c, 0x0a, 0x07, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x12, 0x1e,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xed,
	0xf7, 0x9e, 0x27, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x6f, 0x2e, 0x6b, 0x69, 0x74,
	0x2e, 0x53, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x52, 0x07, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65,
	0x72, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x78, 0x36, 0x34, 0x66, 0x75, 0x6e, 0x2f, 0x74, 0x65, 0x72, 0x72, 0x61, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x6b, 0x69, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kit_swagger_proto_rawDescOnce sync.Once
	file_kit_swagger_proto_rawDescData = file_kit_swagger_proto_rawDesc
)

func file_kit_swagger_proto_rawDescGZIP() []byte {
	file_kit_swagger_proto_rawDescOnce.Do(func() {
		file_kit_swagger_proto_rawDescData = protoimpl.X.CompressGZIP(file_kit_swagger_proto_rawDescData)
	})
	return file_kit_swagger_proto_rawDescData
}

var file_kit_swagger_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kit_swagger_proto_goTypes = []interface{}{
	(*Swagger)(nil),                  // 0: go.kit.Swagger
	(*descriptor.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_kit_swagger_proto_depIdxs = []int32{
	1, // 0: go.kit.swagger:extendee -> google.protobuf.MethodOptions
	0, // 1: go.kit.swagger:type_name -> go.kit.Swagger
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kit_swagger_proto_init() }
func file_kit_swagger_proto_init() {
	if File_kit_swagger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kit_swagger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Swagger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kit_swagger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_kit_swagger_proto_goTypes,
		DependencyIndexes: file_kit_swagger_proto_depIdxs,
		MessageInfos:      file_kit_swagger_proto_msgTypes,
		ExtensionInfos:    file_kit_swagger_proto_extTypes,
	}.Build()
	File_kit_swagger_proto = out.File
	file_kit_swagger_proto_rawDesc = nil
	file_kit_swagger_proto_goTypes = nil
	file_kit_swagger_proto_depIdxs = nil
}
