// Code generated by protoc-gen-go-kit-mux. DO NOT EDIT.
// versions:
// - protoc-gen-go-kit-mux v0.0.1-devel
// - protoc                v3.6.1
package pb

import (
	mux "github.com/gorilla/mux"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the go-kit package it is being compiled against.
// Requires go-kit v0.12.0.

// RegisterKitHTTPExampleHandlerSet - regist all handler
func RegisterKitHTTPExampleHandlerSet(r *mux.Router, set ExampleKitHTTPHandlerSet) {
}
