// Code generated by protoc-gen-go-kit. DO NOT EDIT.
// versions:
// - protoc-gen-go-kit v0.0.1-devel
// - protoc            v3.6.1
package pb

import (
	endpoint "github.com/go-kit/kit/endpoint"
	grpc "github.com/go-kit/kit/transport/grpc"
	http "github.com/go-kit/kit/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the go-kit package it is being compiled against.
// Requires go-kit v0.12.0.

// ExampleKitClient is the go-kit client API for Example service.
type ExampleKitClient interface {
}

type exampleKitClient struct {
	s ExampleKitEndpointSet
}

func NewExampleKitClient(s ExampleKitEndpointSet) ExampleKitClient {
	return &exampleKitClient{s}
}

// ExampleKitServer is the server API for Example service.
// All implementations must embed UnimplementedExampleKitServer
// for forward compatibility
type ExampleKitServer interface {
	mustEmbedUnimplementedExampleKitServer()
}

// UnimplementedExampleKitServer must be embedded to have forward compatible implementations.
type UnimplementedExampleKitServer struct {
}

func (UnimplementedExampleKitServer) mustEmbedUnimplementedExampleKitServer() {}

// UnsafeExampleKitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleKitServer will
// result in compilation errors.
type UnsafeExampleKitServer interface {
	mustEmbedUnimplementedExampleKitServer()
}

// ExampleKitEndpointSet is realize kit/endpoint.Endpoint
type ExampleKitEndpointSet struct {
}

func NewExampleKitEndpointSet(srv ExampleKitServer, mws ...endpoint.Middleware) ExampleKitEndpointSet {
	set := ExampleKitEndpointSet{}
	for _, mw := range mws {
		_ = mw
	}
	return set
}

// ExampleKitHTTPTransport defined from kit/transport/http.
type ExampleKitHTTPTransport interface {
}

// ExampleKitGRPCTransport defined from kit/transport/grpc.
type ExampleKitGRPCTransport interface {
}

// ExampleKitHTTPHandlerSet is realize kit/transport/http.Server set.
type ExampleKitHTTPHandlerSet struct {
	HelloHandler *http.Server
}

func NewExampleKitHTTPHandlerSet(
	set ExampleKitEndpointSet,
	transport ExampleKitHTTPTransport,
	opts ...http.ServerOption,
) ExampleKitHTTPHandlerSet {
	s := ExampleKitHTTPHandlerSet{}
	return s
}

// ExampleKitGRPCHandlerSet is realize kit/transport/grpc.Server set.
type ExampleKitGRPCHandlerSet struct {
	HelloHandler *grpc.Server
}

func NewExampleKitGRPCHandlerSet(
	set ExampleKitEndpointSet,
	transport ExampleKitGRPCTransport,
	opts ...grpc.ServerOption,
) ExampleKitGRPCHandlerSet {
	s := ExampleKitGRPCHandlerSet{}
	return s
}
