// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// V0Client is the client API for V0 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type V0Client interface {
	// 健康检查
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type v0Client struct {
	cc grpc.ClientConnInterface
}

func NewV0Client(cc grpc.ClientConnInterface) V0Client {
	return &v0Client{cc}
}

func (c *v0Client) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/pb.V0/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// V0Server is the server API for V0 service.
// All implementations must embed UnimplementedV0Server
// for forward compatibility
type V0Server interface {
	// 健康检查
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedV0Server()
}

// UnimplementedV0Server must be embedded to have forward compatible implementations.
type UnimplementedV0Server struct {
}

func (UnimplementedV0Server) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedV0Server) mustEmbedUnimplementedV0Server() {}

// UnsafeV0Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to V0Server will
// result in compilation errors.
type UnsafeV0Server interface {
	mustEmbedUnimplementedV0Server()
}

func RegisterV0Server(s grpc.ServiceRegistrar, srv V0Server) {
	s.RegisterService(&V0_ServiceDesc, srv)
}

func _V0_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V0Server).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.V0/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V0Server).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// V0_ServiceDesc is the grpc.ServiceDesc for V0 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var V0_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.V0",
	HandlerType: (*V0Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _V0_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v0.proto",
}
