// Code generated by protoc-gen-go-kit-mux. DO NOT EDIT.
// versions:
// - protoc-gen-go-kit-mux v0.0.1-devel
// - protoc                v3.6.1
package pb

import (
	mux "github.com/gorilla/mux"
	power "github.com/x64fun/terra/example/pb/power"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the go-kit package it is being compiled against.
// Requires go-kit v0.12.0.

// Health godoc
// @Summary Health
// @Description 健康检查
// @Tags v0
// @Accept json
// @Produce json
// @Param id path string true "部门ID"
// @Success 200 {object} util.HTTPObjectResponse{data=basic.Department} "成功"
// @Router /v0/health
func RegisterKitHTTPV0HealthHandler(r *mux.Router, set V0KitHTTPHandlerSet) {
	r.Methods(power.PowerHealth.Method()).Path(power.PowerHealth.MuxPath()).Handler(set.HealthHandler)
}

// RegisterKitHTTPV0HandlerSet - regist all handler
func RegisterKitHTTPV0HandlerSet(r *mux.Router, set V0KitHTTPHandlerSet) {
	RegisterKitHTTPV0HealthHandler(r, set)
}
