// Code generated by protoc-gen-go-kit-mux. DO NOT EDIT.
// versions:
// - protoc-gen-go-kit-mux v0.0.1-devel
// - protoc                v3.6.1
package pb

import (
	mux "github.com/gorilla/mux"
	power "github.com/x64fun/terra/example/pb/power"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the go-kit package it is being compiled against.
// Requires go-kit v0.12.0.

// GetDepartment godoc
func RegisterKitHTTPV1GetDepartmentHandler(r *mux.Router, set V1KitHTTPHandlerSet) {
	r.Methods(power.PowerGetDepartment.Method()).Path(power.PowerGetDepartment.MuxPath()).Handler(set.GetDepartmentHandler)
}

// RegisterKitHTTPV1HandlerSet - regist all handler
func RegisterKitHTTPV1HandlerSet(r *mux.Router, set V1KitHTTPHandlerSet) {
	RegisterKitHTTPV1GetDepartmentHandler(r, set)
}
